version: '3'
services:
  client:
    image: sebastianneumair/htmx-rust:${TAG:-main}
    environment:
      - TAG=main
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:8080"

